name = "hcs-7-toolkit-demo"
compatibility_date = "2024-01-01"

[build]
command = "yarn build"
output_directory = ".next"

[site]
bucket = ".next/static"
entry-point = "."

[env.production]
workers_dev = true
